name: bump-version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[skip]')"

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GA_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: setup git
        run: |
          git config user.name "rvhonorato"
          git config user.email 'rvhonorato@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GA_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"

      - name: setup env variables
        run: |
          echo "SKIPBUMP=FALSE" >> $GITHUB_ENV

      - name: install bump2version
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: bump2version major
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump2version major
          echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        if: "startsWith(github.event.head_commit.message, '[major]')"

      - name: bump2version minor
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump2version minor
          echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        if: "startsWith(github.event.head_commit.message, '[feature]')"

      - name: bump2version patch
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump2version patch
        if: env.SKIPBUMP == 'FALSE'

      - name: push tag to github
        run: |
          git push --follow-tags
